# Generated by Django 4.2.29 on 2026-03-25 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Species",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(blank=True)),
                ("common_name", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("water_interval", models.IntegerField()),
                ("light_req", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_file", models.ImageField(blank=True, upload_to="")),
                ("nickname", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("location", models.TextField(blank=True)),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rootrecord.species",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CareTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("due", models.DateTimeField()),
                ("completed", models.BooleanField(default=False)),
                ("task", models.TextField(blank=True)),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rootrecord.plant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CareLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("image_file", models.ImageField(blank=True, upload_to="")),
                (
                    "care_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rootrecord.caretask",
                    ),
                ),
            ],
        ),
    ]
